"""Added required tables

Revision ID: 4cca5ac1ce4b
Revises: 
Create Date: 2023-05-30 18:14:10.549829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cca5ac1ce4b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zoom_webhook_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event', sa.String(length=40), nullable=True),
    sa.Column('event_ts', sa.BigInteger(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('zoom_webhook_events')
    # ### end Alembic commands ###
